// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 000001_init_scheme.down.sql (30B)
// 000001_init_scheme.up.sql (289B)

package migrations

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_init_schemeDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x28\xca\xcf\x4a\x4d\x2e\x29\xb6\x06\x04\x00\x00\xff\xff\x0d\xe6\x41\x51\x1e\x00\x00\x00")

func _000001_init_schemeDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_schemeDownSql,
		"000001_init_scheme.down.sql",
	)
}

func _000001_init_schemeDownSql() (*asset, error) {
	bytes, err := _000001_init_schemeDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_scheme.down.sql", size: 30, mode: os.FileMode(0644), modTime: time.Unix(1693399223, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb9, 0x7c, 0xaf, 0xb1, 0x11, 0xec, 0x47, 0x8d, 0xa2, 0x74, 0xeb, 0x33, 0x8e, 0xad, 0x67, 0xac, 0x81, 0x91, 0x70, 0x9d, 0x90, 0x83, 0xe2, 0x4b, 0xd8, 0x8c, 0x72, 0x29, 0x79, 0x10, 0x67, 0xe}}
	return a, nil
}

var __000001_init_schemeUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\xca\xd1\x4a\x86\x30\x18\x87\xf1\x73\xaf\xe2\x8f\x47\x0a\xdd\xc4\x3b\x7d\xa5\xd1\xda\x6a\x6e\x91\x47\x22\x3a\xc2\xb2\x29\x36\xef\x3f\xb0\x20\xe8\x3b\xf1\xf4\x79\x7e\x95\x65\x72\x0c\x47\x42\x31\x64\x03\x6d\x1c\xf8\x55\xb6\xae\x45\xbe\xed\xeb\x7b\x18\xd3\x57\x8e\x22\x03\x00\x59\x43\x28\x23\x4e\xa3\xbd\x52\x77\x67\x5d\xe6\xf8\x81\x17\xb2\xd5\x3d\xd9\x7f\x6b\x5c\x63\x1a\xe6\x18\xf6\x3e\x0e\x9f\xe1\x06\xc1\x6b\xf9\xec\xf9\xc7\x1e\x5b\x9f\xd6\x7e\x1a\x52\x80\x30\x46\x31\xe9\x3f\x57\x73\x43\x5e\x39\x34\xa4\xda\x5f\xbe\x1f\x31\xce\xf1\xed\x92\x9d\xc2\x12\x52\x98\x2e\xd9\x27\x2b\x1f\xc9\x76\x78\xe0\xae\x90\x75\x99\x95\xdf\x01\x00\x00\xff\xff\x06\x68\x9e\xfb\x21\x01\x00\x00")

func _000001_init_schemeUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_schemeUpSql,
		"000001_init_scheme.up.sql",
	)
}

func _000001_init_schemeUpSql() (*asset, error) {
	bytes, err := _000001_init_schemeUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_scheme.up.sql", size: 289, mode: os.FileMode(0644), modTime: time.Unix(1693416627, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe5, 0xcf, 0xe4, 0x58, 0x57, 0xb9, 0x42, 0x94, 0x90, 0xe0, 0x96, 0xef, 0x91, 0x17, 0xbc, 0x62, 0x83, 0x6b, 0xde, 0x76, 0x65, 0xca, 0x0, 0x6f, 0xd2, 0xfe, 0x16, 0x74, 0xb8, 0x4e, 0x0, 0xb}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_init_scheme.down.sql": _000001_init_schemeDownSql,
	"000001_init_scheme.up.sql":   _000001_init_schemeUpSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"000001_init_scheme.down.sql": {_000001_init_schemeDownSql, map[string]*bintree{}},
	"000001_init_scheme.up.sql":   {_000001_init_schemeUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
