CREATE TABLE IF NOT EXISTS "projects" (
    ID BLOB NOT NULL,
    link VARCHAR NOT NULL,
    container_name VARCHAR NOT NULL UNIQUE,
    up_to_date BOOLEAN NOT NULL DEFAULT FALSE,
    running BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ID)
)